name: LuciMarie
favicon: null
layout_spectrum: 0.3405574082862586
typography_spectrum: 0.26612522290088236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.11616013897582889
  lightness: 0.2559624877758324
  saturation: 0.8271797380875796
  rhythmicContrast: 0.10697178612463176
purpose: []
